# Site parameters

social:
  linkedin: "www.linkedin.com/in/hasnain-khan-572b6a409"
  github: "https://github.com/hassanhasnain301-hue"
  fiverr: "https://fiverr.com/hasnain_khan_31"
  email: "hassanhasnain481@gmail.com"

hugoblox:
  branding:
    name: "Hasnain Khan"
    description: "Web Developer and Guest Post Specialist"

features:
  dark_mode: true
avatar: "avatar.jpg"
